import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/homepage/Navbar";

const switzer = localFont({
  display: 'swap',
  src: './fonts/Switzer.ttf',
  variable: '--font-switzer',
});

export const metadata: Metadata = {
  title: "Timeless",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${switzer.variable} font-switzer antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
